apiVersion: v1
kind: Secret
metadata:
    name: ibis-fe-secret
type: Opaque
data:
    # You can include additional key value pairs as you do with Opaque Secrets
    salt: {{ .Values.salt }}
    passwd.csv: {{ .Values.passwd }}
