apiVersion: v1
kind: Service
metadata:
  labels:
    app: ibis
  name: ibis
  namespace: default
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: ibis
  sessionAffinity: None
  type: ClusterIP
