apiVersion: v1
kind: Secret
metadata:
    name: ibis-scheduler-secret
type: kubernetes.io/ssh-auth
data:
    # the data is abbreviated in this example
    ssh-privatekey: |
        {{ .Values.sshKey }}
